/** 심볼 → 종목명/시장/섹터 매핑 (Yahoo Finance 심볼 기준) */
export const STOCK_INFO: Record<string, { name: string; market: string; sector: string }> = {
  // ── KOSPI ──────────────────────────────────────────────────────────────────
  '005930.KS': { name: '삼성전자',         market: 'KOSPI', sector: '반도체' },
  '000660.KS': { name: 'SK하이닉스',       market: 'KOSPI', sector: '반도체' },
  '207940.KS': { name: '삼성바이오로직스', market: 'KOSPI', sector: '바이오' },
  '005380.KS': { name: '현대자동차',       market: 'KOSPI', sector: '자동차' },
  '373220.KS': { name: 'LG에너지솔루션',   market: 'KOSPI', sector: '전기차배터리' },
  '000270.KS': { name: '기아',             market: 'KOSPI', sector: '자동차' },
  '005490.KS': { name: 'POSCO홀딩스',      market: 'KOSPI', sector: '철강' },
  '035420.KS': { name: 'NAVER',            market: 'KOSPI', sector: 'IT' },
  '068270.KS': { name: '셀트리온',         market: 'KOSPI', sector: '바이오' },
  '051910.KS': { name: 'LG화학',           market: 'KOSPI', sector: '화학' },
  '105560.KS': { name: 'KB금융',           market: 'KOSPI', sector: '금융' },
  '035720.KS': { name: '카카오',           market: 'KOSPI', sector: 'IT' },
  '055550.KS': { name: '신한지주',         market: 'KOSPI', sector: '금융' },
  '086790.KS': { name: '하나금융지주',     market: 'KOSPI', sector: '금융' },
  '028260.KS': { name: '삼성물산',         market: 'KOSPI', sector: '건설·무역' },
  '066570.KS': { name: 'LG전자',           market: 'KOSPI', sector: '전자' },
  '012330.KS': { name: '현대모비스',       market: 'KOSPI', sector: '자동차부품' },
  '003670.KS': { name: '포스코퓨처엠',     market: 'KOSPI', sector: '2차전지소재' },
  '323410.KS': { name: '카카오뱅크',       market: 'KOSPI', sector: '인터넷은행' },
  '032830.KS': { name: '삼성생명',         market: 'KOSPI', sector: '보험' },
  '017670.KS': { name: 'SK텔레콤',         market: 'KOSPI', sector: '통신' },
  '030200.KS': { name: 'KT',               market: 'KOSPI', sector: '통신' },
  '003490.KS': { name: '대한항공',         market: 'KOSPI', sector: '항공' },
  '096770.KS': { name: 'SK이노베이션',     market: 'KOSPI', sector: '에너지' },
  '033780.KS': { name: 'KT&G',             market: 'KOSPI', sector: '담배·식품' },
  // ── KOSPI 추가 ──────────────────────────────────────────────────────────────
  '009150.KS': { name: '삼성전기',              market: 'KOSPI', sector: '전자부품' },
  '011070.KS': { name: 'LG이노텍',             market: 'KOSPI', sector: '전자부품' },
  '042700.KS': { name: '한미반도체',           market: 'KOSPI', sector: '반도체장비' },
  '000990.KS': { name: 'DB하이텍',             market: 'KOSPI', sector: '반도체' },
  '018260.KS': { name: '삼성SDS',              market: 'KOSPI', sector: 'IT서비스' },
  '036570.KS': { name: 'NC소프트',             market: 'KOSPI', sector: '게임' },
  '251270.KS': { name: '넷마블',               market: 'KOSPI', sector: '게임' },
  '035760.KS': { name: 'CJ ENM',               market: 'KOSPI', sector: '미디어·콘텐츠' },
  '064350.KS': { name: '현대로템',             market: 'KOSPI', sector: '방산·철도' },
  '086280.KS': { name: '현대글로비스',         market: 'KOSPI', sector: '물류' },
  '011210.KS': { name: '현대위아',             market: 'KOSPI', sector: '자동차부품' },
  '018880.KS': { name: '한온시스템',           market: 'KOSPI', sector: '자동차부품' },
  '204320.KS': { name: '만도',                 market: 'KOSPI', sector: '자동차부품' },
  '161390.KS': { name: '한국타이어앤테크놀로지', market: 'KOSPI', sector: '타이어' },
  '002350.KS': { name: '넥센타이어',           market: 'KOSPI', sector: '타이어' },
  '012450.KS': { name: '한화에어로스페이스',   market: 'KOSPI', sector: '방산·항공우주' },
  '316140.KS': { name: '우리금융지주',         market: 'KOSPI', sector: '금융' },
  '071050.KS': { name: '한국금융지주',         market: 'KOSPI', sector: '금융' },
  '024110.KS': { name: 'IBK기업은행',          market: 'KOSPI', sector: '금융' },
  '006800.KS': { name: '미래에셋증권',         market: 'KOSPI', sector: '증권' },
  '016360.KS': { name: '삼성증권',             market: 'KOSPI', sector: '증권' },
  '088350.KS': { name: '한화생명',             market: 'KOSPI', sector: '보험' },
  '000810.KS': { name: '삼성화재',             market: 'KOSPI', sector: '보험' },
  '005830.KS': { name: 'DB손해보험',           market: 'KOSPI', sector: '보험' },
  '001450.KS': { name: '현대해상',             market: 'KOSPI', sector: '보험' },
  '029780.KS': { name: '삼성카드',             market: 'KOSPI', sector: '금융' },
  '138040.KS': { name: '메리츠금융지주',       market: 'KOSPI', sector: '금융' },
  '010950.KS': { name: 'S-Oil',                market: 'KOSPI', sector: '에너지·정유' },
  '009830.KS': { name: '한화솔루션',           market: 'KOSPI', sector: '에너지·화학' },
  '011170.KS': { name: '롯데케미칼',           market: 'KOSPI', sector: '화학' },
  '010060.KS': { name: 'OCI홀딩스',            market: 'KOSPI', sector: '화학' },
  '011780.KS': { name: '금호석유화학',         market: 'KOSPI', sector: '화학' },
  '002380.KS': { name: 'KCC',                  market: 'KOSPI', sector: '건자재·화학' },
  '004800.KS': { name: '효성',                 market: 'KOSPI', sector: '화학·섬유' },
  '003600.KS': { name: 'SK케미칼',             market: 'KOSPI', sector: '화학·바이오' },
  '004020.KS': { name: '현대제철',             market: 'KOSPI', sector: '철강' },
  '010120.KS': { name: 'LS ELECTRIC',          market: 'KOSPI', sector: '전기기기' },
  '006260.KS': { name: 'LS',                   market: 'KOSPI', sector: '전선·소재' },
  '010130.KS': { name: '고려아연',             market: 'KOSPI', sector: '비철금속' },
  '000670.KS': { name: '영풍',                 market: 'KOSPI', sector: '비철금속' },
  '000100.KS': { name: '유한양행',             market: 'KOSPI', sector: '제약' },
  '128940.KS': { name: '한미약품',             market: 'KOSPI', sector: '제약' },
  '326030.KS': { name: 'SK바이오팜',           market: 'KOSPI', sector: '바이오' },
  '302440.KS': { name: 'SK바이오사이언스',     market: 'KOSPI', sector: '바이오' },
  '008930.KS': { name: '한미사이언스',         market: 'KOSPI', sector: '제약' },
  '009420.KS': { name: '한올바이오파마',       market: 'KOSPI', sector: '바이오' },
  '170900.KS': { name: '동아쏘시오홀딩스',     market: 'KOSPI', sector: '제약' },
  '185750.KS': { name: '종근당',               market: 'KOSPI', sector: '제약' },
  '032640.KS': { name: 'LG유플러스',           market: 'KOSPI', sector: '통신' },
  '000720.KS': { name: '현대건설',             market: 'KOSPI', sector: '건설' },
  '006360.KS': { name: 'GS건설',               market: 'KOSPI', sector: '건설' },
  '294870.KS': { name: 'HDC현대산업개발',      market: 'KOSPI', sector: '건설' },
  '034020.KS': { name: '두산에너빌리티',       market: 'KOSPI', sector: '중공업' },
  '028050.KS': { name: '삼성E&A',              market: 'KOSPI', sector: 'EPC' },
  '047040.KS': { name: '대우건설',             market: 'KOSPI', sector: '건설' },
  '012630.KS': { name: 'HDC',                  market: 'KOSPI', sector: '지주' },
  '000210.KS': { name: 'DL',                   market: 'KOSPI', sector: '지주·건설' },
  '139480.KS': { name: '이마트',               market: 'KOSPI', sector: '유통' },
  '023530.KS': { name: '롯데쇼핑',             market: 'KOSPI', sector: '유통' },
  '004170.KS': { name: '신세계',               market: 'KOSPI', sector: '유통' },
  '097950.KS': { name: 'CJ제일제당',           market: 'KOSPI', sector: '식품' },
  '004370.KS': { name: '농심',                 market: 'KOSPI', sector: '식품' },
  '003230.KS': { name: '삼양식품',             market: 'KOSPI', sector: '식품' },
  '005180.KS': { name: '빙그레',               market: 'KOSPI', sector: '식품' },
  '001680.KS': { name: '대상',                 market: 'KOSPI', sector: '식품' },
  '271560.KS': { name: '오리온',               market: 'KOSPI', sector: '식품' },
  '069960.KS': { name: '현대백화점',           market: 'KOSPI', sector: '유통' },
  '008770.KS': { name: '호텔신라',             market: 'KOSPI', sector: '면세·호텔' },
  '007070.KS': { name: 'GS리테일',             market: 'KOSPI', sector: '유통' },
  '000120.KS': { name: 'CJ대한통운',           market: 'KOSPI', sector: '물류' },
  '021240.KS': { name: '코웨이',               market: 'KOSPI', sector: '생활가전' },
  '000080.KS': { name: '하이트진로',           market: 'KOSPI', sector: '주류' },
  '005300.KS': { name: '롯데칠성음료',         market: 'KOSPI', sector: '음료' },
  '090430.KS': { name: '아모레퍼시픽',         market: 'KOSPI', sector: '화장품' },
  '002790.KS': { name: '아모레G',              market: 'KOSPI', sector: '지주' },
  '009540.KS': { name: '한국조선해양',         market: 'KOSPI', sector: '조선' },
  '042660.KS': { name: '한화오션',             market: 'KOSPI', sector: '조선' },
  '010620.KS': { name: '현대미포조선',         market: 'KOSPI', sector: '조선' },
  '011200.KS': { name: 'HMM',                  market: 'KOSPI', sector: '해운' },
  '003550.KS': { name: 'LG',                   market: 'KOSPI', sector: '지주' },
  '034730.KS': { name: 'SK',                   market: 'KOSPI', sector: '지주' },
  '000880.KS': { name: '한화',                 market: 'KOSPI', sector: '지주' },
  '001040.KS': { name: 'CJ',                   market: 'KOSPI', sector: '지주' },
  '078930.KS': { name: 'GS',                   market: 'KOSPI', sector: '지주' },
  '047050.KS': { name: '포스코인터내셔널',     market: 'KOSPI', sector: '무역' },
  '004990.KS': { name: '롯데지주',             market: 'KOSPI', sector: '지주' },
  '001740.KS': { name: 'SK네트웍스',           market: 'KOSPI', sector: '유통' },
  '007340.KS': { name: '강원랜드',             market: 'KOSPI', sector: '카지노' },
  '036460.KS': { name: '한국가스공사',         market: 'KOSPI', sector: '에너지' },
  '015760.KS': { name: '한국전력',             market: 'KOSPI', sector: '전력' },
  '017800.KS': { name: '현대엘리베이터',       market: 'KOSPI', sector: '기계' },
  '112610.KS': { name: '씨에스윈드',           market: 'KOSPI', sector: '풍력' },
  '009450.KS': { name: '경동나비엔',           market: 'KOSPI', sector: '보일러' },
  // ── KOSDAQ ─────────────────────────────────────────────────────────────────
  '247540.KQ': { name: '에코프로비엠',     market: 'KOSDAQ', sector: '2차전지소재' },
  '086520.KQ': { name: '에코프로',         market: 'KOSDAQ', sector: '2차전지소재' },
  '196170.KQ': { name: '알테오젠',         market: 'KOSDAQ', sector: '바이오' },
  '091990.KQ': { name: '셀트리온헬스케어', market: 'KOSDAQ', sector: '바이오' },
  '041510.KQ': { name: 'SM엔터테인먼트',  market: 'KOSDAQ', sector: '엔터' },
  '035900.KQ': { name: 'JYP Ent.',         market: 'KOSDAQ', sector: '엔터' },
  '122870.KQ': { name: '와이지엔터테인먼트', market: 'KOSDAQ', sector: '엔터' },
  '357780.KQ': { name: '솔브레인',         market: 'KOSDAQ', sector: '반도체소재' },
  '293490.KQ': { name: '카카오게임즈',     market: 'KOSDAQ', sector: '게임' },
  '263750.KQ': { name: '펄어비스',         market: 'KOSDAQ', sector: '게임' },
  '112040.KQ': { name: '위메이드',         market: 'KOSDAQ', sector: '게임' },
  '053800.KQ': { name: '안랩',             market: 'KOSDAQ', sector: '보안' },
  '028300.KQ': { name: 'HLB',              market: 'KOSDAQ', sector: '바이오' },
  '145020.KQ': { name: '휴젤',             market: 'KOSDAQ', sector: '의료·바이오' },
  '214150.KQ': { name: '클래시스',         market: 'KOSDAQ', sector: '의료기기' },
  '039030.KQ': { name: '이오테크닉스',     market: 'KOSDAQ', sector: '반도체장비' },
  '078340.KQ': { name: '컴투스',           market: 'KOSDAQ', sector: '게임' },
  '095660.KQ': { name: '네오위즈',         market: 'KOSDAQ', sector: '게임' },
  '091810.KQ': { name: '티웨이항공',       market: 'KOSDAQ', sector: '항공' },
  '034230.KQ': { name: '파라다이스',       market: 'KOSDAQ', sector: '카지노' },
  '048260.KQ': { name: '오스템임플란트',   market: 'KOSDAQ', sector: '치과' },
  '041830.KQ': { name: '인바디',           market: 'KOSDAQ', sector: '의료기기' },
  '066970.KQ': { name: '엘앤에프',         market: 'KOSDAQ', sector: '2차전지소재' },
  '068760.KQ': { name: '셀트리온제약',     market: 'KOSDAQ', sector: '제약' },
  '078600.KQ': { name: '대주전자재료',     market: 'KOSDAQ', sector: '2차전지소재' },
  '067310.KQ': { name: '하나마이크론',     market: 'KOSDAQ', sector: '반도체패키징' },
  '046080.KQ': { name: '웹젠',             market: 'KOSDAQ', sector: '게임' },
  // KOSDAQ 추가 ─────────────────────────────────────────────────────────────
  // 바이오/헬스케어
  '328130.KQ': { name: '루닛',             market: 'KOSDAQ', sector: 'AI의료' },
  '950130.KQ': { name: '엑셀세라퓨틱스', market: 'KOSDAQ', sector: '바이오' },
  '141080.KQ': { name: '레고켐바이오',    market: 'KOSDAQ', sector: '바이오' },
  '950200.KQ': { name: '파마리서치',      market: 'KOSDAQ', sector: '바이오' },
  '085660.KQ': { name: '차바이오텍',      market: 'KOSDAQ', sector: '바이오' },
  '237690.KQ': { name: '에스티팜',        market: 'KOSDAQ', sector: '바이오' },
  '214370.KQ': { name: '케어젠',          market: 'KOSDAQ', sector: '의료·바이오' },
  '084990.KQ': { name: '헬릭스미스',      market: 'KOSDAQ', sector: '바이오' },
  '226950.KQ': { name: '올릭스',          market: 'KOSDAQ', sector: '바이오' },
  '310210.KQ': { name: '보로노이',         market: 'KOSDAQ', sector: '바이오' },
  '088980.KQ': { name: '마크로젠',        market: 'KOSDAQ', sector: '유전체분석' },
  '060280.KQ': { name: '큐렉소',          market: 'KOSDAQ', sector: '의료로봇' },
  '187220.KQ': { name: '디알텍',          market: 'KOSDAQ', sector: '의료기기' },
  '019540.KQ': { name: '제이브이엠',      market: 'KOSDAQ', sector: '의료기기' },
  // 반도체/IT장비
  '403870.KQ': { name: 'HPSP',            market: 'KOSDAQ', sector: '반도체장비' },
  '058470.KQ': { name: '리노공업',        market: 'KOSDAQ', sector: '반도체소재' },
  '240810.KQ': { name: '원익IPS',         market: 'KOSDAQ', sector: '반도체장비' },
  '064760.KQ': { name: '티씨케이',        market: 'KOSDAQ', sector: '반도체소재' },
  '089150.KQ': { name: '케이씨텍',        market: 'KOSDAQ', sector: '반도체장비' },
  '095340.KQ': { name: 'ISC',             market: 'KOSDAQ', sector: '반도체패키징' },
  '039440.KQ': { name: '에스티아이',      market: 'KOSDAQ', sector: '반도체장비' },
  '160980.KQ': { name: '싸이맥스',        market: 'KOSDAQ', sector: '반도체장비' },
  '053610.KQ': { name: '프로텍',          market: 'KOSDAQ', sector: '반도체장비' },
  '036830.KQ': { name: '솔브레인홀딩스', market: 'KOSDAQ', sector: '반도체소재' },
  '121550.KQ': { name: '비에이치',        market: 'KOSDAQ', sector: '전자부품' },
  '131970.KQ': { name: '두산테스나',      market: 'KOSDAQ', sector: '반도체' },
  // 2차전지
  '278280.KQ': { name: '천보',            market: 'KOSDAQ', sector: '2차전지소재' },
  '066970.KQ': { name: '엘앤에프',        market: 'KOSDAQ', sector: '2차전지소재' },
  '222080.KQ': { name: '씨아이에스',      market: 'KOSDAQ', sector: '2차전지장비' },
  '459190.KQ': { name: '에코앤드림',      market: 'KOSDAQ', sector: '2차전지소재' },
  '107640.KQ': { name: '한중엔시에스',    market: 'KOSDAQ', sector: '2차전지장비' },
  // IT/플랫폼
  '052300.KQ': { name: '더존비즈온',      market: 'KOSDAQ', sector: 'IT서비스' },
  '069080.KQ': { name: '웹케시',          market: 'KOSDAQ', sector: '핀테크' },
  '039420.KQ': { name: '사람인에이치알', market: 'KOSDAQ', sector: 'IT서비스' },
  '225570.KQ': { name: '넥슨게임즈',      market: 'KOSDAQ', sector: '게임' },
  '064440.KQ': { name: '이스트소프트',    market: 'KOSDAQ', sector: 'IT·AI' },
  // 방산/에너지
  '272210.KQ': { name: '한화시스템',      market: 'KOSDAQ', sector: '방산' },
  '336260.KQ': { name: '두산퓨얼셀',      market: 'KOSDAQ', sector: '수소에너지' },
  '267260.KQ': { name: 'HD현대일렉트릭', market: 'KOSDAQ', sector: '전기기기' },
  '082740.KQ': { name: 'HSD엔진',         market: 'KOSDAQ', sector: '조선엔진' },
  // 소비재/기타
  '192400.KQ': { name: '쿠쿠홀딩스',      market: 'KOSDAQ', sector: '가전' },
  '307950.KQ': { name: '현대오토에버',    market: 'KOSDAQ', sector: 'IT서비스' },
  '272290.KQ': { name: '이엔드디',        market: 'KOSDAQ', sector: '2차전지소재' },
  '024770.KQ': { name: '키다리스튜디오', market: 'KOSDAQ', sector: '웹툰·콘텐츠' },
  // ── NASDAQ ─────────────────────────────────────────────────────────────────
  'AAPL':  { name: 'Apple',              market: 'NASDAQ', sector: '소비자전자' },
  'MSFT':  { name: 'Microsoft',          market: 'NASDAQ', sector: '소프트웨어' },
  'NVDA':  { name: 'NVIDIA',             market: 'NASDAQ', sector: '반도체' },
  'GOOGL': { name: 'Alphabet',           market: 'NASDAQ', sector: '인터넷' },
  'META':  { name: 'Meta Platforms',     market: 'NASDAQ', sector: '소셜미디어' },
  'AMZN':  { name: 'Amazon',             market: 'NASDAQ', sector: 'e-커머스' },
  'TSLA':  { name: 'Tesla',              market: 'NASDAQ', sector: '전기차' },
  'AVGO':  { name: 'Broadcom',           market: 'NASDAQ', sector: '반도체' },
  'NFLX':  { name: 'Netflix',            market: 'NASDAQ', sector: '스트리밍' },
  'AMD':   { name: 'AMD',                market: 'NASDAQ', sector: '반도체' },
  'QCOM':  { name: 'Qualcomm',           market: 'NASDAQ', sector: '반도체' },
  'INTC':  { name: 'Intel',              market: 'NASDAQ', sector: '반도체' },
  'MU':    { name: 'Micron Technology',  market: 'NASDAQ', sector: '반도체' },
  'AMAT':  { name: 'Applied Materials',  market: 'NASDAQ', sector: '반도체장비' },
  'LRCX':  { name: 'Lam Research',       market: 'NASDAQ', sector: '반도체장비' },
  'ASML':  { name: 'ASML',               market: 'NASDAQ', sector: '반도체장비' },
  'COST':  { name: 'Costco',             market: 'NASDAQ', sector: '유통' },
  'ADBE':  { name: 'Adobe',              market: 'NASDAQ', sector: '소프트웨어' },
  'PYPL':  { name: 'PayPal',             market: 'NASDAQ', sector: '핀테크' },
  'TXN':   { name: 'Texas Instruments',  market: 'NASDAQ', sector: '반도체' },
  // ── NYSE ───────────────────────────────────────────────────────────────────
  'JPM':   { name: 'JPMorgan Chase',     market: 'NYSE', sector: '금융' },
  'V':     { name: 'Visa',               market: 'NYSE', sector: '금융결제' },
  'MA':    { name: 'Mastercard',         market: 'NYSE', sector: '금융결제' },
  'WMT':   { name: 'Walmart',            market: 'NYSE', sector: '유통' },
  'XOM':   { name: 'ExxonMobil',         market: 'NYSE', sector: '에너지' },
  'JNJ':   { name: 'Johnson & Johnson',  market: 'NYSE', sector: '헬스케어' },
  'UNH':   { name: 'UnitedHealth',       market: 'NYSE', sector: '헬스케어' },
  'HD':    { name: 'Home Depot',         market: 'NYSE', sector: '유통' },
  'BAC':   { name: 'Bank of America',    market: 'NYSE', sector: '금융' },
  'KO':    { name: 'Coca-Cola',          market: 'NYSE', sector: '음료' },
  'MRK':   { name: 'Merck',              market: 'NYSE', sector: '제약' },
  'PG':    { name: 'Procter & Gamble',   market: 'NYSE', sector: '생활용품' },
  'CVX':   { name: 'Chevron',            market: 'NYSE', sector: '에너지' },
  'ABBV':  { name: 'AbbVie',             market: 'NYSE', sector: '제약' },
  'WFC':   { name: 'Wells Fargo',        market: 'NYSE', sector: '금융' },
  'TMO':   { name: 'Thermo Fisher',      market: 'NYSE', sector: '헬스케어' },
  'NKE':   { name: 'Nike',               market: 'NYSE', sector: '스포츠' },
  'MCD':   { name: "McDonald's",         market: 'NYSE', sector: '외식' },
  'PM':    { name: 'Philip Morris',      market: 'NYSE', sector: '담배' },
}
